- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/dto/response/NoticeListDtoByApp.java
- src/main/java/org/dongguk/jjoin/service/ClubService.java
동아리 게시글 목록 보기를 구현했으나
해당 유저가 동아리 회원일 경우만 공지글을 확인할 수 있기에, 추후에 **로그인이 구현되면 사용자가 해당 club의 멤버가 아닐 경우 공지 게시판 접근이 불가능하게 하는 로직이 추가되어야 할 것 같습니다.**
> [FEAT] 동아리 게시글 구현 (앱) https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/22
> ✨ Feat: 동아리 게시글 구현 (앱)

- src/main/java/org/dongguk/jjoin/service/ManagerService.java
관리자 웹페이지에서 게시글 리스트를 확인할때 삭제된 리스트도 보여져서
게시글 목록을 불러올때 삭제된 리스트를 제외하는 로직을 추가했습니다.
> [FIX] 삭제된 게시글 목록보이는 버그 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/23
> 🐛 Fix: showNoticeList 수정

- src/main/java/org/dongguk/jjoin/controller/SearchController.java
- src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java
- src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
- src/main/java/org/dongguk/jjoin/repository/ClubTagRepository.java
- src/main/java/org/dongguk/jjoin/repository/TagRepository.java
- src/main/java/org/dongguk/jjoin/service/SearchService.java
앱 화면에서 동아리 검색결과로 보여줄 화면에 필요한 API를 구현합니다.
- 일반 검색
- 키워드 검색
- 태그 검색
- 키워드+태그 검색
**관련 이슈** 
> [FEAT] 동아리 검색 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/26
**고려해봐야할 부분**
> 검색 조건으로 여러개의 태그를 설정할 경우 검색시에 해당 태그를 하나라도 만족하는(OR) 동아리들을 검색해오도록 구현을 했는데, 여러개의 태그를 모두 만족하는(AND) 동아리만 검색해오는게 좀 더 맞는 것 같기도해서 수정할까 고민 중입니다.
그러나 태그를 만들때 서로 관련성 없는 태그로 만들면 기존의 방식(OR)로 해도 상관없을 것 같습니다.
> ✨ Feat : 동아리 검색 API 구현

- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubAlbumDetailDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDetailDto.java
- src/main/java/org/dongguk/jjoin/service/AlbumService.java
- src/main/java/org/dongguk/jjoin/service/ScheduleService.java
앱 화면에서 일정 및 사진첩 상세페이지로 보여줄 화면에 필요한 API를 구현합니다.
- 일정 상세정보
- 사진 리스트 및 사진첩 생성 일자
**관련 이슈** 
> [FEAT] 일정, 사진첩 상세페이지 API 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/30
**고려해봐야할 부분**
> 이미지를 넘겨주는 부분에서 이미지의 uuid만 넘겨주면 되는지 잘 모르겠습니다. 이미지 업로드 방식에 대해서 공부한 후에 다시 수정하도록 하겠습니다.
> ✨ Feat : App - 일정 상세 및 사진첩 상세 API 구현

- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/domain/ClubMember.java
- src/main/java/org/dongguk/jjoin/domain/User.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubMemberDtoByWeb.java
- src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
- src/main/java/org/dongguk/jjoin/service/ManagerService.java
관리자 웹에서 동아리 관리자가 본인의 동아리 멤버 목록, 권한, 퇴출하는 기능을 구현합니다.
추가로 User table에 학번 정보를 저장할 student_Id column을 추가하여 커밋하였습니다.
- 멤버 목록
- 멤버 권한 수정
- 멤버 퇴출
**관련 이슈 **
> #33 
**고려해봐야할 사항**
>  해당 기능을 사용하기 위해 로그인된 유저의 권한을 확인하는 부분이 추가되어야합니다.
> ✨ Feat : Web - 동아리 멤버 관리 API 구현

- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/domain/Plan.java
- src/main/java/org/dongguk/jjoin/dto/request/PlanRequestDto.java
- src/main/java/org/dongguk/jjoin/dto/request/PlanUpdateDto.java
- src/main/java/org/dongguk/jjoin/dto/response/PlanDto.java
- src/main/java/org/dongguk/jjoin/service/PlanService.java
웹 일정 화면에 필요한 API를 구현합니다.
- 일정 목록 조회
- 일정 추가
- 일정 수정
- 일정 삭
**관련 이슈** 
> [FEAT] Web - 동아리 일정 API 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/42
**고려해봐야할 부분**
> 일정 삭제 부분에서 일정 삭제를 hard delete 방식으로 삭제를 진행했습니다. 이를 plan에 단순히 isDeleted를 추가해서 soft delete 방식으로 바꿀건지 논의가 필요합니다.
> ✨ Feat : App - 일정 API 구현

- src/main/java/org/dongguk/jjoin/controller/AdminController.java
- src/main/java/org/dongguk/jjoin/domain/Club.java
- src/main/java/org/dongguk/jjoin/domain/Enrollment.java
- src/main/java/org/dongguk/jjoin/domain/User.java
- src/main/java/org/dongguk/jjoin/dto/request/EnrollmentUpdateDto.java
- src/main/java/org/dongguk/jjoin/dto/response/EnrollmentDto.java
- src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
- src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
웹 일정 화면에 필요한 API를 구현합니다.
- 동아리 개설 목록 조회
- 동아리 개설 승인
- 동아리 개설 거
**관련 이슈** 
> [FEAT] Web - 동아리 개설 API 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/44
**고려해봐야할 부분**
> 동아리 개설 승인 시 이를 club의 createDate에 날짜를 할당하는 방식으로 동아리 개설을 표현했기때문에 앞서서 **동아리 조회를 할때 모두 createDate가 null이 아닌 동아리만 조회하도록 변경해야합니다.**(해당 조건이 빠질 경우 아직 개설이 되지 않은 동아리도 조회가 됨). 또한 승인 거부를 할 시 해당 데이터가 반영된 후 삭제되는데(hard delete) 이 방식에 대해서는 다시 생각해봐야할 것 같습니다.
> ✨ Feat : Web - 일정 API 구현

- src/main/java/org/dongguk/jjoin/controller/AdminController.java
- src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java
- src/main/java/org/dongguk/jjoin/dto/request/ClubDeletionUpdateDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubDeletionDto.java
- src/main/java/org/dongguk/jjoin/repository/ClubDeletionRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubDeletionService.java
동아리 삭제 화면에 필요한 API를 구현합니다.
- 동아리 삭제 목록 조회
- 동아리 삭제
**관련 이슈** 
> [FEAT] Web - 동아리 삭제 API 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/48
**고려해봐야할 부분**
> 앞서서 **동아리 조회를 할때 모두 ClubDeletion의 isDeleted가 True가 아닌 동아리만 조회하도록 변경해야합니다.**(해당 조건이 빠질 경우 삭제된 동아리도 조회가 됨).
> ✨ Feat : Web - 동아리 삭제 API 구현

- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/domain/Club.java
- src/main/java/org/dongguk/jjoin/domain/type/DependentType.java
- src/main/java/org/dongguk/jjoin/dto/request/ClubEnrollmentRequestDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentResponseDto.java
- src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
- src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
동아리 개설신청 화면에 필요한 API를 구현합니다.
- 동아리 개설 신청서 목록 조회
- 동아리 개설 신청
- 동아리 개설 신청서 조회 
**관련 이슈** 
> [FEAT] Web - 동아리 개설 신청 API 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/49
**고려해봐야할 부분**
> 개설 거부를 당했을 시 관련 데이터를 모두 삭제할 수 있도록 개설 API를 수정하겠습니다.
> ✨ Feat : Web - 동아리 개설 신청 API 구현

- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/dto/request/ApplicationAnswerDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ApplicationFormDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ApplicationQuestionDto.java
- src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
- src/main/java/org/dongguk/jjoin/repository/QuestionRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubService.java
앱에서 동아리 가입하기 위해 신청서를 조회하고 작성하는 API를 구현합니다.
- **관련 이슈**
> #54 
**고려해봐야할 부분**
> 동아리 가입 신청서 제출시에 User 정보를 저장하는 로직이 필요한데 로그인 구현 이후에 추가해야할 것 같습니다.
> ✨ Feat: App - 동아리 가입신청서 API 구현

- src/main/java/org/dongguk/jjoin/controller/AdminController.java
- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/domain/Club.java
- src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java
- src/main/java/org/dongguk/jjoin/domain/Enrollment.java
- src/main/java/org/dongguk/jjoin/dto/request/ClubDeletionUpdateDto.java
- src/main/java/org/dongguk/jjoin/dto/request/EnrollmentUpdateDto.java
- src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java
- src/main/java/org/dongguk/jjoin/repository/ClubDeletionRepository.java
- src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
- src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubDeletionService.java
- src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
- src/main/java/org/dongguk/jjoin/service/SearchService.java
AdminController에서 다루는 동아리 개설 신청서 조회에 대한 페이징 처리 추가와 개설 신청 승인, 거부에서 발생할 수 있는 버그를 수정했습니다. 또한 동아리 삭제 신청서 조회에 대한 페이징 처리 추가와, 삭제 신청 승인에서 발생할 수 있는 버그를 수정했습니다. 또한 기존에 개설되지 않거나 삭제된 동아리에 대해서도 모든 동아리 조회가 가능했는데 이제부터는 삭제된 동아리와 개설되지 않은 동아리에 대해서는 조회가 불가능하도록 쿼리문을 수정하였습니다.
- 개설 신청서 조회 페이징 처리
- 개설 신청 승인 및 거부 버그 수정
- 삭제 신청서 조회 페이징 처리
- 삭제 신청 승인 버그 수정
- 개설되지 않거나 삭제된 동아리는 조회 시 제외
**관련 이슈** 
> [FIX] 쿼리문 수정 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/57
**고려해봐야할 부분**
> 혹시라도 삭제된 동아리나 개설되지 않은 동아리 조회되는 버그가 발견된다면 발견하는 대로 수정하도록 하겠습니다. 또한 개설되지않고 삭제되지 않은 동아리에 대해서 조회하지 않도록 쿼리를 수정하여서 메소드명이 굉장히 길어지고 쿼리문도 복잡해졌는데 이 부분에 대해서 리팩토링을 어떻게 진행할지 고민하도록 해보겠습니다.
> 🐛 Fix: AdminController 관련 메소드 수정

- src/main/java/org/dongguk/jjoin/controller/AdminController.java
- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentResponseDto.java
- src/main/java/org/dongguk/jjoin/dto/response/JoinedClubDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ManagingClubDto.java
- src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
- src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
- src/main/java/org/dongguk/jjoin/service/ManagerService.java
관리자 웹에서 관리자가 관리하는 동아리들을 보여주는 API를 구현합니다.
\+ 추가로 admin측 개설신청 상세보기도 구현하였습니다.
- 관리하는 동아리 조회 API 구현
- Admin측 개설신청 상세조회 API 구현
**관련 이슈**
> #61 
**고려해봐야할 부분**
> 로그인 구현시 현재 로그인 되어 있는 유저 id를 바탕으로 clubd을 조회해오기 때문에 그 부분에 대한 수정이 필요합니다.
> ✨ Feat: Web - 관리자가 관리하는 동아리 조회 API 구현

- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/controller/UserController.java
- src/main/java/org/dongguk/jjoin/dto/request/ClubEnrollmentRequestDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubCardDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubEnrollmentResponseDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDetailDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ScheduleDayDto.java
- src/main/java/org/dongguk/jjoin/dto/response/UserClubDto.java
- src/main/java/org/dongguk/jjoin/dto/response/UserProfileDto.java
- src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubService.java
- src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
- src/main/java/org/dongguk/jjoin/service/ScheduleService.java
- src/main/java/org/dongguk/jjoin/service/UserService.java
마이페이지에서의 API와 앱 홈화면에서 가입하 동아리 조회, 매니저의 개설신청서 CRUD에서 발생할 수 있는 버그를 수정했습니다.
- 가입한 동아리
- 사용자 조회
- 사용자 동아리 조회
- 프로필 변경
- 회원 탈퇴
- 동아리 개설 신청서 목록 조회
- 동아리 개설
- 동아리 개설 신청서 조회
**관련 이슈** 
> [FIX] 마이페이지 및 동아리 조회, 개설신청서 CRUD 수정 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/72
**고려해봐야할 부분**
> 아마도 계속해서 버그가 발생할 것 같아서 통합 테스트를 한번 해야할 것 같습니다.
> 🐛 Fix: 마이페이지 및 동아리 조회, 개설신청서 CRUD 수정

- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/controller/SearchController.java
- src/main/java/org/dongguk/jjoin/dto/page/ApplicationPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/ClubMemberPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/NoticeAppPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/NoticeWebPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/PageInfo.java
- src/main/java/org/dongguk/jjoin/dto/page/SearchClubPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/TagPageDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ClubMemberDto.java
- src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java
- src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java
- src/main/java/org/dongguk/jjoin/repository/ClubRepository.java
- src/main/java/org/dongguk/jjoin/repository/NoticeRepository.java
- src/main/java/org/dongguk/jjoin/repository/TagRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubService.java
- src/main/java/org/dongguk/jjoin/service/ManagerService.java
- src/main/java/org/dongguk/jjoin/service/SearchService.java
페이지네이션이 필요한 API의 ResponseBody에 페이지네이션 정보를 담아서 반환합니다.
App
- 동아리 검색
- 동아리 검색시 태그 목록
- 동아리 게시글 목록
Web
- 게시글 목록
- 가입 신청 목록
- 멤버 목록 조회
**관련 이슈**
> #89
> 🐛 Fix : ResponseDto에 페이지네이션 정보 추가

- src/main/java/org/dongguk/jjoin/dto/response/ClubMemberDto.java
- src/main/java/org/dongguk/jjoin/service/ManagerService.java
Web에서 동아리 멤버 조회시 email을 반환해줘야하는데 누락되어있어 추가해서 반환하도록 수정합니다.
**관련 이슈**
> #93
> 🐛 Fix : 동아리 멤버 조회시 email 값 추가해서 반환

- src/main/java/org/dongguk/jjoin/controller/AdminController.java
- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/controller/ManagerController.java
- src/main/java/org/dongguk/jjoin/dto/page/ClubDeletionPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/ClubEnrollmentPageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/ClubSchedulePageDto.java
- src/main/java/org/dongguk/jjoin/dto/page/EnrollmentPageDto.java
- src/main/java/org/dongguk/jjoin/dto/response/ManagingClubDto.java
- src/main/java/org/dongguk/jjoin/repository/EnrollmentRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubDeletionService.java
- src/main/java/org/dongguk/jjoin/service/EnrollmentService.java
- src/main/java/org/dongguk/jjoin/service/ManagerService.java
- src/main/java/org/dongguk/jjoin/service/ScheduleService.java
동아리 관리자 페이지에서 사진 및 동아리 정보를 추가적으로 전달했고 pageInfo가 전달 안되던 부분도 다 추가해주었습니다.
- 동아리 관리자 메인 페이지 추가 정보 전달
- pageInfo 추가 전달
- 
**관련 이슈** 
[FEAT] 동아리 관리자 페이지 정보 추가 및 pageInfo 추가 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/95
**고려해봐야할 부분**
페이징과 관련하여 dto 하나하나마다 추가할 필요없이 공통적으로 사용할 dto를 하나만들면 좋을 것 같습니다:)
> ✨ Feat: Web - 동아리 관리자 페이지 정보 추가 및 pageInfo 추가

- src/main/java/org/dongguk/jjoin/controller/ClubController.java
- src/main/java/org/dongguk/jjoin/dto/response/NoticeListDto.java
- src/main/java/org/dongguk/jjoin/service/ManagerService.java
- src/main/java/org/dongguk/jjoin/service/ScheduleService.java
동아리 게시글 번호가 꼬이는 문제를 해결했습니다.
- 기존에 updateDate로 정렬하던 것을 createdDate 정렬로 수정
- 게시글 번호를 따로 계산하여 추
**관련 이슈** 
[FIX] 게시글 번호 꼬임 문제 해결 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/98
**고려해봐야할 부분**
> 🐛 FIX: Web - 게시글 번호 꼬임 문제 해결

- src/main/java/org/dongguk/jjoin/repository/NoticeRepository.java
- src/main/java/org/dongguk/jjoin/service/ClubService.java
초기에 짰던 동아리 게시글 조회하는 로직을 NoticeRepository를 활용해서 최적화할 수 있도록 수정하겠습니다.
추가로 앱에서 동아리 가입신청 지원시에 @GetUser로 로그인된 유저의 정보를 따와서 제출해야하는데 로그인이 아직 구현되지 않아 무조건 userId = 8 으로 지원신청이 되도록 코드를 수정했습니다.
> [REFACTOR] Web - 동아리 게시글 리팩토링

- src/main/java/org/dongguk/jjoin/domain/type/DependentType.java
현재 동아리 타입인 DependentType에 학과(MAJOR), 중앙(CENTER) 동아리 밖에 없는데 연합 동아리 타입도 추가합니다.
**관련 이슈**
> #104
> 🐛 FIX : 동아리 타입에 연합동아리 추가

- src/main/java/org/dongguk/jjoin/domain/Recruited_period.java
모집 기간에서 OR로 표현되어야 할 식이 AND도 표현되어 있어서 수정했습니다.
- startDate와 endDate 비교에서 현재 날짜가 endDate보다 이후거나 startDate보다 이전이라면 모집 종료로 수정
**관련 이슈** 
[FIX] 모집 기간 오류 수정 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/107
**고려해봐야할 부분**
> 🐛 FIX: Web - 유저 정보 및 동아리 정보 수정 오류 해결
