In-lyeog-sa-mu-so/jjoin-server

src/main/java/org/dongguk/jjoin/domain/Group.java, src/main/java/org/dongguk/jjoin/domain/Group_application.java, src/main/java/org/dongguk/jjoin/domain/Group_member.java, src/main/java/org/dongguk/jjoin/domain/Group_tag.java, src/main/java/org/dongguk/jjoin/domain/Recruited_period.java, src/main/java/org/dongguk/jjoin/domain/Tag.java, src/main/java/org/dongguk/jjoin/domain/User.java, src/main/java/org/dongguk/jjoin/domain/type/DependentType.java, src/main/java/org/dongguk/jjoin/domain/type/ELoginProvider.java, src/main/java/org/dongguk/jjoin/domain/type/EUserRole.java, src/main/java/org/dongguk/jjoin/domain/type/RankType.java
Entity Part2 생성.
Group Entity의 image 프로퍼티,
Recruited의 joincolumn,
User Entity 줄간격 수정했습니다
=> ✨ Feat: 엔티티 생성 Part2 (Group, Recruited, User Entity 수정)

src/main/java/org/dongguk/jjoin/domain/Album.java, src/main/java/org/dongguk/jjoin/domain/Enrollment.java, src/main/java/org/dongguk/jjoin/domain/Event.java, src/main/java/org/dongguk/jjoin/domain/GroupDeletion.java, src/main/java/org/dongguk/jjoin/domain/Image.java, src/main/java/org/dongguk/jjoin/domain/Notice.java, src/main/java/org/dongguk/jjoin/domain/Schedule.java, src/main/java/org/dongguk/jjoin/domain/type/ImageType.java
=> ✨ Feat: 엔티티 생성 Part1

src/main/java/org/dongguk/jjoin/domain/Album.java, src/main/java/org/dongguk/jjoin/domain/Enrollment.java, src/main/java/org/dongguk/jjoin/domain/Event.java, src/main/java/org/dongguk/jjoin/domain/Group.java, src/main/java/org/dongguk/jjoin/domain/GroupApplication.java, src/main/java/org/dongguk/jjoin/domain/GroupMember.java, src/main/java/org/dongguk/jjoin/domain/GroupTag.java, src/main/java/org/dongguk/jjoin/domain/Notice.java, src/main/java/org/dongguk/jjoin/domain/Schedule.java, src/main/java/org/dongguk/jjoin/domain/Tag.java, src/main/java/org/dongguk/jjoin/domain/User.java
1:N 단방향 관계를 해결할 좋은 방법을 떠올리지 못해 일단은 구현에 집중해서
N:1 양방향으로 설정했으나 차후 이 부분에 대한 리펙토링이 필요할 듯 합니다....
=> 🎨 Refactor: Entity Part1,2 연결 및 연관관계 설정

src/main/java/org/dongguk/jjoin/domain/Album.java, src/main/java/org/dongguk/jjoin/domain/Club.java, src/main/java/org/dongguk/jjoin/domain/ClubApplication.java, src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java, src/main/java/org/dongguk/jjoin/domain/ClubMember.java, src/main/java/org/dongguk/jjoin/domain/ClubTag.java, src/main/java/org/dongguk/jjoin/domain/Enrollment.java, src/main/java/org/dongguk/jjoin/domain/Image.java, src/main/java/org/dongguk/jjoin/domain/Notice.java, src/main/java/org/dongguk/jjoin/domain/Plans.java, src/main/java/org/dongguk/jjoin/domain/Recruited_period.java, src/main/java/org/dongguk/jjoin/domain/Schedule.java, src/main/java/org/dongguk/jjoin/domain/Tag.java, src/main/java/org/dongguk/jjoin/domain/User.java, src/main/resources/application.properties
Entity에서 기존에 MySQL에 존재하는 예약어와 겹치는 컬럼명을 수정했습니다.
그리고 local db와 연동하기 위해 application.properties에 간단한 설정을 추가했습니다.
=> 🎨 Refactor: Entity 예약어 수정 및 로컬 db연동 설정 추가

src/main/java/org/dongguk/jjoin/domain/Club.java, src/main/java/org/dongguk/jjoin/domain/ClubApplication.java, src/main/java/org/dongguk/jjoin/domain/ClubDeletion.java, src/main/java/org/dongguk/jjoin/domain/ClubMember.java, src/main/java/org/dongguk/jjoin/domain/ClubTag.java, src/main/java/org/dongguk/jjoin/domain/Plan.java, src/main/java/org/dongguk/jjoin/domain/Recruited_period.java, src/main/java/org/dongguk/jjoin/domain/Schedule.java, src/main/java/org/dongguk/jjoin/domain/User.java
=> 🎨 Refactor: Entity 컬럼명 및 클래스 명 수정

src/main/java/org/dongguk/jjoin/dto/request/NoticeRequestDto.java, src/main/java/org/dongguk/jjoin/dto/response/NoticeDto.java, src/main/java/org/dongguk/jjoin/dto/response/NoticeListDto.java, src/main/java/org/dongguk/jjoin/repository/ClubRepository.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java
저번 PR에서 누락, 변경사항 댓글에 달아놨던거 추가해서 올립니다. 
- 공지글 공개범위 설정부분 수정
- 누락된 NoticeDto, NoticeListDto 추가
- 누락된 clubRepository 추가
=> ✨ Feat: 동아리 공지 누락 파일 추가 및 수정

src/main/java/org/dongguk/jjoin/controller/ClubController.java, src/main/java/org/dongguk/jjoin/dto/response/ClubAlbumDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubDetailDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDto.java, src/main/java/org/dongguk/jjoin/dto/response/ScheduleDayDto.java, src/main/java/org/dongguk/jjoin/repository/AlbumRepository.java, src/main/java/org/dongguk/jjoin/repository/PlanRepository.java, src/main/java/org/dongguk/jjoin/repository/RecruitedPeriodRepository.java, src/main/java/org/dongguk/jjoin/service/AlbumService.java, src/main/java/org/dongguk/jjoin/service/ClubService.java, src/main/java/org/dongguk/jjoin/service/ScheduleService.java
동아리를 클릭했을 경우 보이는 동아리 상세화면에 필요한 API들을 구현 완료했습니다.
동아리 공지 부분의 경우 이미 @nicolao00 가 구현을 완료했습니다.
**일정이나 사진첩을 클릭했을때 나오는 UI 및 API는 추가적인 개발이 필요합니다.**
=> ✨ Feat: 동아리 상세 API 구현

src/main/java/org/dongguk/jjoin/controller/UserController.java, src/main/java/org/dongguk/jjoin/domain/User.java, src/main/java/org/dongguk/jjoin/dto/request/UserProfileUpdateDto.java, src/main/java/org/dongguk/jjoin/dto/response/UserClubDto.java, src/main/java/org/dongguk/jjoin/dto/response/UserProfileDto.java, src/main/java/org/dongguk/jjoin/service/ClubService.java, src/main/java/org/dongguk/jjoin/service/UserService.java
마이페이지 화면에 필요한 API를 구현합니다.
- 사용자 프로필 정보
- 사용자가 가입한 동아리
- 프로필 변경
- 회원 탈퇴
**관련 이슈** 
> [FEAT] App- 동아리 마이페이지 API 구현 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/37
**고려해봐야할 부분**
> 앱 설정 및 앱 정보 부분은 프로토타입인 관계로 구현하지 않았습니다. 또한 프로필 변경에서 현재 사용자의 프로필을 가져와야 하는데 이 또한 현재 구현해놓지 않은 상태입니다. 향후 시간이 남으면 다시 자세하게 API 명세를 해서 개발을 실시하도록 하겠습니다.
=> ✨ Feat : App - 마이페이지 API 구현

src/main/java/org/dongguk/jjoin/controller/ManagerController.java, src/main/java/org/dongguk/jjoin/domain/Recruited_period.java, src/main/java/org/dongguk/jjoin/dto/ClubMemberDtoByWeb.java, src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageDtoByWeb.java, src/main/java/org/dongguk/jjoin/repository/ClubRepository.java, src/main/java/org/dongguk/jjoin/repository/ImageRepository.java, src/main/java/org/dongguk/jjoin/repository/RecruitedPeriodRepository.java, src/main/java/org/dongguk/jjoin/service/ClubService.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java, src/main/java/org/dongguk/jjoin/service/SearchService.java
웹에서 동아리 메인페이지와 관련된 기능을 구현합니다
- 기존 메인페이지 조회
- 메인페이지 수정
**관련 이슈**
> [FEAT] App- 동아리 마이페이지 API 구현 #43 
**고려해봐야할 부분**
> Spring Boot에서 JSON으로 전달된 타임스탬프 값을 MySQL DATETIME 필드에 저장할 때, Spring Boot의 기본적인 동작은 UTC 타임존을 사용하여 저장한다고 합니다. 그래서 입력한 값 "2023-09-21T15:30:00Z"는 UTC로 해석되어 "2023-09-22 00:30:00.000000"으로 변환되어 저장되는 문제가 발생했는데 추후에 이 부분에 대해 해결이 필요할 것 같습니다. 
\+ 이미지 수정하고 저장하는 방식에 대한 부분도 추가가 필요합니다.
=> ✨ Feat : Web - 동아리 메인페이지 API 구현

src/main/java/org/dongguk/jjoin/domain/Application_answer.java, src/main/java/org/dongguk/jjoin/domain/Application_question.java, src/main/java/org/dongguk/jjoin/domain/Club.java, src/main/java/org/dongguk/jjoin/domain/ClubApplication.java
동아리 지원서 관련 Table을 추가하였습니다.
**관련 이슈**
> [FEAT] 동아리 지원서 테이블 추가 #38 
**고려해봐야할 부분**
>  추후에 선택형 질문, 이미지 답변 다양한 기능 추가
=> ✨ Feat : Web - 동아리 지원서 관련 Table 추가

src/main/java/org/dongguk/jjoin/controller/ManagerController.java, src/main/java/org/dongguk/jjoin/domain/Application_answer.java, src/main/java/org/dongguk/jjoin/domain/Application_question.java, src/main/java/org/dongguk/jjoin/dto/request/ApplicationQuestionDto.java, src/main/java/org/dongguk/jjoin/dto/response/ApplicationDetailDto.java, src/main/java/org/dongguk/jjoin/dto/response/ApplicationDto.java, src/main/java/org/dongguk/jjoin/dto/response/ApplicationQAset.java, src/main/java/org/dongguk/jjoin/repository/AnswerRepository.java, src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java, src/main/java/org/dongguk/jjoin/repository/QuestionRepository.java, src/main/java/org/dongguk/jjoin/repository/UserRepository.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java
동아리 지원서 관련 기능을 추가하였습니다.
(가입 신청서 질문 생성,  가입 신청서 상세보기, 목록, 신청 수락, 거절 기능)
> **_Application_answer Entity 수정 사항(User 외래키 추가) 꼭 인지해주시기 바랍니다_**
**관련 이슈**
> #32 
**고려해봐야할 부분**
>
=> ✨ Feat : Web - 동아리 가입 신청 API 구현

src/main/java/org/dongguk/jjoin/controller/ClubController.java, src/main/java/org/dongguk/jjoin/controller/ManagerController.java, src/main/java/org/dongguk/jjoin/domain/Recruited_period.java, src/main/java/org/dongguk/jjoin/domain/User.java, src/main/java/org/dongguk/jjoin/dto/request/UserTagDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubDetailDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageDtoByWeb.java, src/main/java/org/dongguk/jjoin/dto/response/ClubRecommendDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDetailDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubScheduleDto.java, src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java, src/main/java/org/dongguk/jjoin/repository/ClubTagRepository.java, src/main/java/org/dongguk/jjoin/repository/PlanRepository.java, src/main/java/org/dongguk/jjoin/repository/RecruitedPeriodRepository.java, src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java, src/main/java/org/dongguk/jjoin/service/ClubService.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java, src/main/java/org/dongguk/jjoin/service/PlanService.java, src/main/java/org/dongguk/jjoin/service/ScheduleService.java, src/main/java/org/dongguk/jjoin/service/SearchService.java
ClubController에서 전체적인 서비스 수정이 있었습니다. 일정 조회에서 페이징 기능을 추가하였고, DTO의 이름들을 전반적으로 수정했습니다.
- 동아리 상세 조회 수정
- 동아리 게시글 목록 조회 수정
- 동아리 게시글 상세 조회 수정
- 동아리 일정 목록 조회 수정
- 동아리 일정 상세 조회 수정
- 동아리 사진첩 조회 수정
- 동아리 사진첩 상세 조회 수정
- 추천 동아리 조회 수정
**관련 이슈** 
> [FIX] ClubController 수정 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/60
**고려해봐야할 부분**
> 아마도 계속해서 버그가 발생할 것 같아서 통합 테스트를 한번 해야할 것 같습니다.
=> 🐛 Fix: ClubController 버그 수정

src/main/java/org/dongguk/jjoin/controller/SearchController.java, src/main/java/org/dongguk/jjoin/dto/response/TagDto.java, src/main/java/org/dongguk/jjoin/repository/TagRepository.java, src/main/java/org/dongguk/jjoin/service/SearchService.java
동아리 검색을 위해 모든 태그 목록을 조회하는 API를 구현했습니다.
**관련 이슈**
> #64 
**고려해봐야할 부분**
>
=> ✨ Feat: App - 동아리 태그 목록 조회 API 구현

src/main/java/org/dongguk/jjoin/repository/PlanRepository.java, src/main/java/org/dongguk/jjoin/service/EnrollmentService.java, src/main/java/org/dongguk/jjoin/service/ScheduleService.java, src/main/resources/application.properties
일정 조회 기능에 빠져있던 페이지 기능과 UTC 시간으로 반영되던 db의 timezone을 서울로 바꿨습니다.
- 일정 조회 페이징 기능
- timezone을 서울로 설정
**관련 이슈** 
> [FEAT] 동아리 일정 조회 페이징 기능 긴급 추가 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/69
**고려해봐야할 부분**
> 아마도 계속해서 버그가 발생할 것 같아서 통합 테스트를 한번 해야할 것 같습니다.
=> ✨ Feat : 일정 조회 페이징 기능 추가 및 프로퍼티 수정

src/main/java/org/dongguk/jjoin/controller/ClubController.java, src/main/java/org/dongguk/jjoin/controller/SearchController.java
API 명세와 다르게 응답 response 프로퍼티가 짜여진 부분이 있어 수정해서 올렸습니다.
**관련 이슈**
> #71 
**고려해봐야할 부분**
>
=> 🐛 FIX: API 명세에 맞게 응답Dto 프로퍼티명 수정

src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java, src/main/java/org/dongguk/jjoin/service/SearchService.java
동아리 가입신청서 목록 조회시에 reponseBody에 applicationId값을 추가로 넘겨주도록 수정했습니다.
또한 isFinished 프로퍼티도 추가했습니다.
**관련 이슈**
> #74
=> 🐛 FIX: App - 동아리 검색시 응답값 LeaderName 추가

src/main/java/org/dongguk/jjoin/dto/response/ApplicationDto.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java
동아리 가입신청서 목록, 상세 조회시에 reponseBody에 applicationId값을 추가로 넘겨주도록 수정합니다.
**관련 이슈**
> #76
=> 🐛 FIX: App 동아리 가입신청서 목록,상세 조회시 Id값 추가

src/main/java/org/dongguk/jjoin/domain/Recruited_period.java, src/main/java/org/dongguk/jjoin/dto/response/ClubDetailDto.java, src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageDtoByWeb.java, src/main/java/org/dongguk/jjoin/dto/response/SearchClubDto.java, src/main/java/org/dongguk/jjoin/service/ClubService.java, src/main/java/org/dongguk/jjoin/service/EnrollmentService.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java, src/main/java/org/dongguk/jjoin/service/SearchService.java
isFinished 속성을 추가하고 시작 날짜와 종료 날짜를 조작할 시 isFinished를 최신화하는 로직을 추가했습니다.
- isFinished 속성 추
**관련 이슈** 
> [FIX] 동아리 모집기간 완료 속성 추가 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/80
**고려해봐야할 부분**
> 아마도 계속해서 버그가 발생할 것 같아서 통합 테스트를 한번 해야할 것 같습니다.
=> 🐛 Fix: 동아리 모집기관 완료 Boolean 속성 추가

src/main/java/org/dongguk/jjoin/controller/AdminController.java, src/main/java/org/dongguk/jjoin/controller/ClubController.java, src/main/java/org/dongguk/jjoin/controller/ManagerController.java, src/main/java/org/dongguk/jjoin/controller/ScheduleController.java, src/main/java/org/dongguk/jjoin/controller/SearchController.java, src/main/java/org/dongguk/jjoin/controller/UserController.java
기존에 그냥 배열로 넘기던 dto를 data로 한번 감싸서 map으로 보냈습니다.
- 배열을 키가 "data"인 map으로 감싸서 전
**관련 이슈** 
[FIX] 페이징 수정, json 수정, DateUtil 수정 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/82
**고려해봐야할 부분**
=> 🐛 Fix: 배열 data 매핑 추가

src/main/java/org/dongguk/jjoin/dto/response/UserProfileDto.java, src/main/java/org/dongguk/jjoin/repository/ScheduleRepository.java, src/main/java/org/dongguk/jjoin/service/ScheduleService.java, src/main/java/org/dongguk/jjoin/service/UserService.java
하루 일정을 반환할때 불참 일정을 제외한 모든 일정을 보내주고, 사용자 정보 조회에서 학번을 추가해습니다.
- 하루 일정 조회 기능 추가
- 사용자 정보 조회 학번 추가
=> ✨ Feat : 하루 일정 반환 수정 및 사용자 학번 정보 추가

src/main/java/org/dongguk/jjoin/controller/ManagerController.java, src/main/java/org/dongguk/jjoin/repository/AnswerRepository.java, src/main/java/org/dongguk/jjoin/repository/ApplicationRepository.java, src/main/java/org/dongguk/jjoin/repository/ClubMemberRepository.java, src/main/java/org/dongguk/jjoin/repository/ClubRepository.java, src/main/java/org/dongguk/jjoin/repository/TagRepository.java
웹에서 동아리 가입 신청서 질문 생성의 endPoint를 수정합니다.
추가로, Repository의 쿼리 메소드에 @param 어노테이션을 전부 추가했습니다.
=> 🐛 Fix : Web - 가입신청서 질문 생성 엔드포인트, 쿼리메소드 Param 추가

src/main/java/org/dongguk/jjoin/controller/ManagerController.java, src/main/java/org/dongguk/jjoin/domain/Application_question.java, src/main/java/org/dongguk/jjoin/dto/request/QuestionDeleteDto.java, src/main/java/org/dongguk/jjoin/dto/request/QuestionModifyDto.java, src/main/java/org/dongguk/jjoin/dto/response/ApplicationFormDto.java, src/main/java/org/dongguk/jjoin/dto/response/ApplicationQuestionResponseDto.java, src/main/java/org/dongguk/jjoin/repository/QuestionRepository.java, src/main/java/org/dongguk/jjoin/service/ClubService.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java
동아리 매니저가 가입신청서를 조회, 수정하는 API를 구현했습니다.
- 가입 신청서 질문 조회
- 가입 신청서 질문 수정
- 가입 신청서 질문 삭제
**관련 이슈**
> #79
=> ✨ Feat: Web - 가입 신청서 질문 관련 API 구현

src/main/java/org/dongguk/jjoin/repository/AnswerRepository.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java
동아리 가입 신청서 정보를 받아오는 과정에서 하나의 답변만 받아와야하는데 여러개의 답변이 받아와지는 버그를 해결했습니다.
- 하나의 답변만 받아오도록 수정
**관련 이슈** 
[FIX] 동아리 가입신청서 버그 수정 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/98
**고려해봐야할 부분**
=> 🐛 FIX: Web - 동아리 가입신청서 버그 수정

src/main/java/org/dongguk/jjoin/domain/Club.java, src/main/java/org/dongguk/jjoin/domain/User.java, src/main/java/org/dongguk/jjoin/dto/response/ClubMainPageUpdateDto.java, src/main/java/org/dongguk/jjoin/service/ManagerService.java, src/main/java/org/dongguk/jjoin/service/UserService.java
동아리 정보를 수정하거나 유저 정보를 수정할때 값을 입력하지 않으면 이에 대한 예외 처리가 이루어지지 않았는데 수정했습니다.
- 동아리 정보 수정 버그 해결
- 유저 정보 수정 버그 해결
**관련 이슈** 
[FIX] 동아리 이미지 수정 오류 해결 https://github.com/In-lyeog-sa-mu-so/jjoin-server/issues/103
**고려해봐야할 부분**
=> 🐛 FIX: Web - 유저 정보 및 동아리 정보 수정 오류 해결

src/main/java/org/dongguk/jjoin/service/SearchService.java
동아리 검색시 로직을 수정하겠습니다.
**관련 이슈**
> #110
=> 🐛 FIX: 동아리 검색 로직 수정
